server:
    port: ${SERVER_PORT:8085}

spring:
    application:
        name: Store

    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/delivery_store}
        username: ${SPRING_DATASOURCE_USERNAME:root}
        password: ${SPRING_DATASOURCE_PASSWORD:root}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        database-platform: org.hibernate.dialect.MySQLDialect

    flyway:
        enabled: true
        table: flyway_schema_history_store
        baseline-on-migrate: true
        baseline-version: 0

    kafka:
        bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        consumer:
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

store:
    order-event:
        order-created-topic: ${STORE_ORDER_EVENT_ORDER_CREATED_TOPIC:outbox.event.OrderCreated}
        order-status-changed-topic: ${STORE_ORDER_EVENT_ORDER_STATUS_CHANGED_TOPIC:outbox.event.OrderStatusChanged}
        order-created-consumer-group: ${STORE_ORDER_EVENT_ORDER_CREATED_CONSUMER_GROUP:store-order-created-validation}
        order-paid-consumer-group: ${STORE_ORDER_EVENT_ORDER_PAID_CONSUMER_GROUP:store-order-paid}

management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
    metrics:
        distribution:
            percentiles-histogram:
                http.server.requests: true
        tags:
            application: ${spring.application.name}

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
