{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "svc_name", "query": { "query": "label_values(up,job)" } }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(up{job=~\"$svc_name\"}) or vector(0)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "50x",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum by (job) (rate(http_server_requests_seconds_count{job=~\"$svc_name\",status=~\"5..\",uri!=\"/actuator/prometheus\"}[5m]))\r\n  /\r\n  clamp_min(sum by (job) (rate(http_server_requests_seconds_count{job=~\"$svc_name\",uri!=\"/actuator/prometheus\"}[5m])), 1)\r\n)\r\n",
     "legendFormat": "{{svc_name}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (\r\n  rate(http_server_requests_seconds_count{\r\n    job=~\"$svc_name\",\r\n    uri!=\"/actuator/prometheus\"\r\n  }[1m])\r\n)\r\n",
     "legendFormat": "{{svc_name}}"
    }
   ]
  },
  {
   "title": "P95",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (job, le) (\r\n    rate(http_server_requests_seconds_bucket{\r\n      job=~\"$svc_name\",\r\n      uri!=\"/actuator/prometheus\"\r\n    }[5m])\r\n  )\r\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "P99",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (job, le) (\r\n    rate(http_server_requests_seconds_bucket{\r\n      job=~\"$svc_name\",\r\n      uri!=\"/actuator/prometheus\"\r\n    }[5m])\r\n  )\r\n)",
     "legendFormat": "{{svc_name}}"
    }
   ]
  },
  {
   "title": "P50",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (job, le) (\r\n    rate(http_server_requests_seconds_bucket{\r\n      job=~\"$svc_name\",\r\n      uri!=\"/actuator/prometheus\"\r\n    }[5m])\r\n  )\r\n)",
     "legendFormat": "{{svc_name}}"
    }
   ]
  }
 ]
}