CREATE DATABASE IF NOT EXISTS delivery_order;
CREATE DATABASE IF NOT EXISTS delivery_user;
CREATE DATABASE IF NOT EXISTS delivery_auth;
CREATE DATABASE IF NOT EXISTS delivery_store;
CREATE DATABASE IF NOT EXISTS delivery_payment;
CREATE DATABASE IF NOT EXISTS delivery_point;
